### PR TITLE
[types] Fix type errors in codebase

### LINKED ISSUE #572: [types] Fix type errors in codebase
There are currently 176 type errors coming from the codebase itself. These are definitely worth fixing (not necessarily before v0.6.0, but at some point), so I'd like some feedback as to the best way to fix certain kinds of type-specific errors (i.e. type errors that aren't actually indicative of a problem with the JS logic).

A relatively common one is `TS2322: Type 'number[]' is not assignable to type '[number, number, number]'`. An example of code causing this can be seen here:

<https://github.com/color-js/color.js/blob/c99665cb2dfb9e1cefb1f6c764a41b9af7cc89e2/src/adapt.js#L72-L74>

Since the return value of `multiplyMatrices` is not specific enough, it causes the aforementioned error. There are a few ways I can think of fixing this.

The first would be to simply ignore the error:

```typescript
// @ts-expect-error
return multiplyMatrices(env.M, env.XYZ);
```

The second would be to assert as the proper type (`[number, number, number]`):

```typescript
return /** @type {[number, number, number]} */ (multiplyMatrices(env.M, env.XYZ));
```

And the third would just be to assert as `any`:

```typescript
return /** @type {any} */ (multiplyMatrices(env.M, env.XYZ));
```

I find it annoying that the type assertions with JSDoc are so ugly, but I'm not sure whether it's worth completely ignoring type checks for a line instead with a `@ts-expect-error` directive. Thoughts?

### PR DESCRIPTION
**Pull request by MysteryBlokHed**
Closes #572

Fixes type errors originating from the codebase itself.

In some instances, the logic was changed where it seemed like the type error reflected an actual problem. For example, adding `color = Color.get(color)` where the signature made it seem as though a function could take `ColorTypes`, but actually couldn't.

### CODE REVIEW

File: src/clone.js [hunk 1]
```diff
@@ -1,15 +1,16 @@
 // Type "imports"
+/** @typedef {import("./color.js").default} Color */
 /** @typedef {import("./types.js").PlainColorObject} PlainColorObject */
 
 /**
  *
- * @param {PlainColorObject} color
+ * @param {Color | PlainColorObject} color
```
Comment (lloydk) [inline src/clone.js:7]: Color implements the `PlainColorObject` so adding `Color` shouldn't be necessary.

File: src/display.js [hunk 2]
```diff
@@ -7,6 +7,7 @@ import REC2020 from "./spaces/rec2020.js";
 import P3 from "./spaces/p3.js";
 import Lab from "./spaces/lab.js";
 import sRGB from "./spaces/srgb.js";
+import Color from "./color.js";
```
Comment (lloydk) [inline src/display.js:10]: The functional interface should never reference the `Color` class.

**Review by lloydk — COMMENTED** [review]
Didn't do a thorough review, added a few comments.

File: src/clone.js (hunk 1 above)
Comment (MysteryBlokHed) [reply src/clone.js:7]: Right—for some reason I keep forgetting that

File: src/display.js (hunk 2 above)
Comment (MysteryBlokHed) [reply src/display.js:10]: Good point. Should I change the signature of the function to only accept `PlainColorObject`, since that seems to be what the function is meant to handle?

Comment (lloydk) [reply src/display.js:10]: `serialize` calls `getColor` on the color so `ColorTypes` should be ok.

Comment (MysteryBlokHed) [reply src/display.js]: Didn't realize that these lines also expect `PlainColorObject`:

<https://github.com/color-js/color.js/blob/c0a48bf283f7858cf589e81f5566a485299aa344/src/display.js#L49-L52>

So I just put the call at the beginning of the function instead.

**Comment by MysteryBlokHed** [comment]
Not 100% sure that the commit I just pushed for `Format` is entirely correct, so any comments would be appreciated

**Comment by lloydk** [comment]
> Not 100% sure that the commit I just pushed for `Format` is entirely correct, so any comments would be appreciated

The `Format` stuff is complicated, I took a look at it last week and gave up after a few hours.

I'll take a closer look after I take the dog for a walk but some stuff that's missing:

- `ColorSpace.getFormat` should return the `Format` class not the `Format` interface.
- The `Format` class should have almost every property from the `Format` interface. see https://github.com/color-js/color.js/blob/c0a48bf283f7858cf589e81f5566a485299aa344/src/Format.js#L36

In the `Format` class I didn't like how the `coords` property changed from an array of strings to `Type[][]` so in the PR that I abandoned I renamed `Format.coords` to `coordTypes`.

**Comment by lloydk** [comment]
The Format changes look good although I'm not 100% sure about the type for `Format.coords`. If `format.type === "custom"` it's `[string, string, string]` otherwise it's `Type[][]`. I think it would be better to have two different properties.

**Comment by MysteryBlokHed** [comment]
> If `format.type === "custom"` it's `[string, string, string]` otherwise it's `Type[][]`. I think it would be better to have two different properties.

Ah, I didn't even notice that. I don't think there's a great way to type it without separating the two properties. We could ask Lea for her thoughts in regards to making a new property, since she wrote the class?

**Comment by lloydk** [comment]
> > If `format.type === "custom"` it's `[string, string, string]` otherwise it's `Type[][]`. I think it would be better to have two different properties.
> 
> Ah, I didn't even notice that. I don't think there's a great way to type it without separating the two properties. We could ask Lea for her thoughts in regards to making a new property, since she wrote the class?

We could just leave it as `Type[][]` since you probably won't have a `coords` property for a custom format.

File: src/ColorSpace.d.ts [hunk 3]
```diff
@@ -16,6 +16,7 @@ export interface Format {
 	id?: string | undefined;
```
Comment (lloydk) [inline src/ColorSpace.d.ts:16]:
```suggestion
	id?: string | undefined;
	ids?: string[] | undefined;
```

The zyz-d65 space uses the `ids` property.

**Comment by MysteryBlokHed** [comment]
Sorry I haven't worked on this for a while, I've been busier than usual. If anybody else wants to push commits to fix errors then feel free—this branch is on the main repository instead of a fork so permissions shouldn't be an issue.

**Comment by LeaVerou** [comment]
Sorry I’ve been absent as well, my thesis defense is in a month so I've been directing all my resources towards it. Should this PR block releasing v0.6.0?

**Comment by lloydk** [comment]
> Sorry I’ve been absent as well, my thesis defense is in a month so I've been directing all my resources towards it. Should this PR block releasing v0.6.0

At the very least we should merge what we have so far in this PR before releasing v0.6.0. I had to switch my project to this branch because I needed some of the fixes in this PR.

**Comment by LeaVerou** [comment]
Does anyone have a sense of what % done this PR is?

**Comment by lloydk** [comment]
> Does anyone have a sense of what % done this PR is?

maybe 80%

**Comment by MysteryBlokHed** [comment]
> At the very least we should merge what we have so far in this PR before releasing v0.6.0.

I agree. We might as well merge what we have so far and worry about the rest of the errors some other time, since most errors don't actually seem to indicate any logical problems in the code.

**Comment by LeaVerou** [comment]
Agreed

**Comment by LeaVerou** [comment]
@MysteryBlokHed should I just merge this then? It's still marked as draft.

**Comment by MysteryBlokHed** [comment]
Oops, I forgot to mark it ready—fixed

File: src/Format.js [hunk 4]
```diff
@@ -98,7 +110,7 @@ export default class Format {
 			if (!type) {
 				// Type does not exist in the grammar, throw
 				let coordName = coordMeta.name || id;
-				throw new TypeError(`${ providedType ?? arg?.raw ?? arg } not allowed for ${coordName} in ${this.name}()`);
+				throw new TypeError(`${ providedType ?? /** @type {any} */ (arg)?.raw ?? arg } not allowed for ${coordName} in ${this.name}()`);
```
Comment (LeaVerou) [inline src/Format.js:113]: Excuse my ignorance, why do we need inline `@type` comments? Is this information we cannot capture in the block jsdoc comments? (a link is fine, I just googled it and couldn't figure it out)

Comment (MysteryBlokHed) [reply src/Format.js:113]: This is how type assertions work when using JSDoc.
Type assertions: <https://www.typescriptlang.org/docs/handbook/2/everyday-types.html#type-assertions>
JSDoc syntax for assertions: <https://www.typescriptlang.org/docs/handbook/jsdoc-supported-types.html#casts>

It's needed whenever TypeScript can't properly determine the type of something within the body of a function (eg. for variables that were defined within that function).

For the line you commented on, TypeScript would complain that the property `raw` doesn't exist on `number`. The easiest way to stop it from complaining was to assert `arg` as `any`, effectively disabling type checking for `arg` on that particular line.

It's also sometimes needed when a function's return type isn't specific enough, like here:

<https://github.com/color-js/color.js/blob/9661dc697426a3983e7d390daea5e49e80291f05/src/RGBColorSpace.js#L42>

Comment (LeaVerou) [reply src/Format.js:113]: Ah, I see, thank you!

**Review by LeaVerou — APPROVED** [review]
LGTM, I think this is a net improvement. Since this is a large one, I suggest we merge soon before stuff gets out of sync.
