### PR TITLE
Fix serialization of negative percentages

### LINKED ISSUE #552: Incorrect serialization of negative values for sRGB and HSL
Negative values are serialized as `-Infinity`.

https://apps.colorjs.io/convert/?color=oklch(0%2C%200.1%2C%20180)&precision=4

image

### PR DESCRIPTION
**Pull request by lloydk**
Closes #552

Changes the hard coded percentage ranges to a variable range based on whether or not the lower bounds of the range is < 0. Spaces that do not have coordinate ranges (e.g. xyz-d65) will have a percentage range of [0, 1] and [0, 100].

### CODE REVIEW

File: src/Type.js [hunk 1]
```diff
@@ -104,6 +105,15 @@ export default class Type {
 		return ret;
 	}
 
+	/**
+	 * Returns a percentage range for values of this type
+	 * @param {number} scale
+	 */
+	pctRange (scale = 1) {
```
Comment (LeaVerou) [inline src/Type.js:112]: I’d rather avoid abbreviations like "pct".
```suggestion
	percentageRange (scale = 1) {
```

**Review by LeaVerou — APPROVED** [review]
Thanks! LGTM, see comment wrt naming.

**Comment by LeaVerou** [comment]
Gah, now this introduces an error, since we changed the name of the function but not of the function calls. The suggestion was indicative, sorry if that wasn't clear!

**Comment by lloydk** [comment]
> Gah, now this introduces an error, since we changed the name of the function but not of the function calls. The suggestion was indicative, sorry if that wasn't clear!

Oops, I was watching tv and wasn't really paying attention.
